import 'dart:io';

import 'package:path/path.dart' as p;

import 'package:forui_cli/src/commands/style/style.dart';
import 'package:forui_cli/src/components/autocomplete_multiselect.dart';
import 'package:forui_cli/src/components/confirm.dart';
import 'package:forui_cli/src/components/log.dart';
import 'package:forui_cli/src/components/select.dart';
import 'package:forui_cli/src/configuration.dart';
import 'package:forui_cli/src/terminal/command.dart';
import 'package:forui_cli/src/terminal/primitives.dart';
import 'package:forui_cli/src/terminal/terminal.dart';
import 'package:forui_cli/src/terminal/text.dart';
import 'package:forui_cli/src/terminal/theme.dart';

const _unnamespaced = '''
import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:material_ui/material_ui.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.''';

const _namespaced = '''
import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:material_ui/material_ui.dart';

import 'package:forui/forui.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// extension CustomFDividerStyles on Never {
///   // Modify this function's body.
///   static FDividerStyles dividerStyles({
///     required FColorScheme color,
///     required FStyle style,
///   }) => FDividerStyles(
///     horizontalStyle: FDividerStyle(
///       colors: colors.secondary,
///       padding: FDividerStyle.defaultPadding.horizontalStyle,
///       width: style.borderWidth,
///     ),
///     verticalStyle: FDividerStyle(
///       colors: colors.secondary,
///       padding: FDividerStyle.defaultPadding.verticalStyle,
///       width: style.borderWidth,
///     ),
///   );
/// }
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.''';

/// Maps every style's lowercased name and aliases to its [Style], for resolving the user's arguments.
final registry = {
  for (final MapEntry(:key, :value) in Style.values.asNameMap().entries) ...{
    key.toLowerCase(): value,
    for (final alias in value.aliases) alias.toLowerCase(): value,
  },
};

class StyleCreateCommand extends ForuiCommand {
  static String _fold(String value) => value.toLowerCase().replaceAll(RegExp('[-_ ]'), '');

  static String _snake(String pascal) =>
      pascal.replaceAllMapped(RegExp('([a-z0-9])([A-Z])'), (m) => '${m[1]}_${m[2]}').toLowerCase();

  static String _camel(String pascal) => pascal[0].toLowerCase() + pascal.substring(1);

  @override
  final name = 'create';

  @override
  final aliases = ['c'];

  @override
  final description = 'Create Forui widget style files.';

  @override
  final arguments = '[style...]';

  final Configuration configuration;

  new(this.configuration) {
    argParser
      ..addFlag('all', abbr: 'a', help: 'Generate all styles.', negatable: false)
      ..addFlag('force', abbr: 'f', help: 'Overwrite existing files if they exist.', negatable: false)
      ..addOption(
        'output',
        abbr: 'o',
        help: 'The output directory or file, relative to the project directory.',
        defaultsTo: configuration.style,
      );
  }

  @override
  void run() {
    ansi.enabled = globalResults!.flag('color');
    truecolor.enabled = globalResults!.flag('color');
    terminal.interactive = !globalResults!.flag('no-input');
    final output = argResults!['output'] as String;
    final all = argResults!.flag('all');
    final rest = argResults!.rest;

    if (rest.isNotEmpty && all) {
      terminal.writeErrorln('Cannot use "[style...]" and "--all" at the same time.');
      exit(1);
    }

    // `autocompleteMultiselect` returns the initial (empty) selection when not interactive, so a script would silently
    // create nothing. Error instead.
    if (rest.isEmpty && !all && !terminal.interactive) {
      terminal.writeErrorln('No style specified. Run "forui style ls" to see all styles.');
      exit(1);
    }

    // Validate explicit arguments up-front, before opening any interactive frame.
    if (rest.isNotEmpty && !_validate(rest)) {
      exit(1);
    }

    if (!terminal.interactive) {
      _generate(all ? Style.values.asNameMap().keys.toList() : rest, output: output);
      return;
    }

    terminal.intro('Create widget styles');

    final styles = switch (all) {
      true => Style.values.asNameMap().keys.toList(),
      false when rest.isNotEmpty => rest,
      false => switch (autocompleteMultiselect<String>(
        message: 'Styles',
        options: {
          '': [
            for (final style in Style.values.toList()..sort((a, b) => a.aliases.first.compareTo(b.aliases.first)))
              SelectOption(style.aliases.first, hint: '(${style.type})'),
          ],
        },
        // Match the type shown in the hint too, and fold `-`, `_`, and spaces together so "autocomplete field",
        // "autocomplete-field", and "autocompletefield" all match.
        filter: (option, query) {
          final q = _fold(query);
          return _fold(option.label).contains(q) || _fold(option.hint!).contains(q);
        },
        min: 1,
        maxItems: 25,
      )) {
        Value(:final value) => value,
        Cancelled() => _cancelled('No styles created.'),
      },
    };

    terminal.outro('Created ${_generate(styles, output: output)} file(s).');
  }

  bool _validate(List<String> styles) {
    var valid = true;
    for (final style in styles) {
      if (registry.containsKey(style.toLowerCase())) {
        continue;
      }

      valid = false;

      final suggestions =
          registry.keys.map((e) => (e, e.startsWith(style) ? 1 : distance(style, e))).where((e) => e.$2 <= 3).toList()
            ..sort((a, b) => a.$2.compareTo(b.$2));

      final buffer = StringBuffer('Could not find a style named "$style".');
      if (suggestions.isNotEmpty) {
        buffer.write('\nDid you mean one of these?');
        for (final (suggestion, _) in suggestions) {
          buffer.write('\n  $suggestion');
        }
      }

      terminal.writeErrorln('$buffer');
    }

    if (!valid) {
      terminal.writeErrorln('Run "forui style ls" to see all styles.');
    }

    return valid;
  }

  /// Generates the style files for [styles] and returns the number of files written. Multiple styles collapse into one
  /// namespaced file when [output] is a `.dart` file.
  int _generate(List<String> styles, {required String output}) {
    final force = argResults!.flag('force');

    final paths = <String, List<String>>{};
    final existing = <String>{};

    for (final style in styles) {
      final file = _snake(registry[style.toLowerCase()]!.type.substring(1));
      final path = p.normalize(
        p.join(configuration.root.path, output.endsWith('.dart') ? output : p.join(output, '$file.dart')),
      );

      (paths[path] ??= []).add(style);
      if (File(path).existsSync()) {
        existing.add(path);
      }
    }

    if (!force && existing.isNotEmpty) {
      if (terminal.interactive) {
        final relative = [
          for (final path in existing.toList()..sort()) p.relative(path, from: configuration.root.path),
        ];
        terminal.warn('The following file(s) will be overwritten:\n\n${relative.join('\n')}');
      }

      final overwrite =
          terminal.interactive && confirm(message: 'Overwrite ${existing.length} existing file(s)?', initial: false);

      if (!overwrite) {
        if (!terminal.interactive) {
          terminal.writeErrorln('${existing.length} file(s) already exist; pass --force to overwrite.');
          exit(1);
        }

        _cancelled('No styles created.');
      }
    }

    // Writes a style's root function plus its privatised nested closures. When [many], wraps them in a
    // `Custom… on Never` extension of `static` members so several styles can share one file without name clashes.
    void reduce(StringBuffer buffer, List<String> closure, {required bool many}) {
      final root = registry[closure.first.toLowerCase()]!;

      if (many) {
        buffer
          ..writeln('extension Custom${root.type} on Never {')
          ..write('static ');
      }
      buffer.writeln(root.source);

      for (final nested in closure.skip(1)) {
        if (many) {
          buffer.write('static ');
        }
        final style = registry[nested.toLowerCase()]!;
        final function = _camel(style.type.substring(1));
        final index = style.source.indexOf(function);
        buffer.write('${style.source.substring(0, index)}_${style.source.substring(index)}\n');
      }

      if (many) {
        buffer.writeln('}');
      }
    }

    for (final MapEntry(key: path, value: group) in paths.entries) {
      final buffer = StringBuffer();

      if (registry[group.first.toLowerCase()] case Style(:final closure) when group.length == 1) {
        buffer.writeln(_unnamespaced);
        reduce(buffer, closure, many: false);
      } else {
        buffer.writeln(_namespaced);
        for (final style in group) {
          reduce(buffer, registry[style.toLowerCase()]!.closure, many: true);
        }
      }

      File(path)
        ..createSync(recursive: true)
        ..writeAsStringSync(formatter.format(buffer.toString()));

      if (!terminal.interactive) {
        terminal.success('Created ${Uri.file(path)}');
      } else {
        terminal.writeln('Created ${Uri.file(path)}');
      }
    }

    return paths.length;
  }

  Never _cancelled(String message) {
    terminal.cancel(message);
    exit(130);
  }
}
