import 'dart:io';

import 'package:path/path.dart' as p;

import 'package:forui_cli/forui_cli.dart';
import 'package:forui_cli/src/commands/theme/theme.dart';
import 'package:forui_cli/src/components/confirm.dart';
import 'package:forui_cli/src/components/log.dart';
import 'package:forui_cli/src/configuration.dart';
import 'package:forui_cli/src/preset/icons.dart';
import 'package:forui_cli/src/preset/typography.dart';
import 'package:forui_cli/src/terminal/terminal.dart';

String _themeHeader(String preset, String? iconImport) =>
    '''
import 'package:forui/forui.dart';
import 'package:material_ui/material_ui.dart';${iconImport == null ? '' : '\n$iconImport'}

part 'colors.dart';
part 'typography.dart';
part 'style.dart';
part 'icons.dart';

/// Generated by Forui CLI.
///
/// Regenerate using "dart forui theme create --preset $preset".
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart run forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.''';

String _colorsHeader(String themeFileName) =>
    '''
part of '$themeFileName';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.''';

String _typographyHeader(String themeFileName) =>
    '''
part of '$themeFileName';

/// Generated by Forui CLI.
///
/// Typography tokens for the generated theme.''';

String _styleHeader(String themeFileName) =>
    '''
part of '$themeFileName';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.''';

String _iconsHeader(String themeFileName) =>
    '''
part of '$themeFileName';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.''';

/// Generates the theme files for [preset] under [output], installing any required fonts and icon packages.
Future<void> create(Configuration configuration, Preset preset, {required bool force, required String output}) async {
  final themePath = p.normalize(
    p.join(configuration.root.path, output.endsWith('.dart') ? output : p.join(output, 'theme.dart')),
  );
  final themeDir = p.dirname(themePath);
  final themeFileName = p.basename(themePath);
  final colorsPath = p.join(themeDir, 'colors.dart');
  final typographyPath = p.join(themeDir, 'typography.dart');
  final stylePath = p.join(themeDir, 'style.dart');
  final iconsPath = p.join(themeDir, 'icons.dart');

  // Check for existing files before doing any download or package work.
  if (!force) {
    final existing = [
      themePath,
      colorsPath,
      typographyPath,
      stylePath,
      iconsPath,
    ].where((path) => File(path).existsSync()).toList();

    if (existing.isNotEmpty) {
      // Non-interactive runs can't prompt, so a conflict is a hard error; interactive runs ask.
      if (!terminal.interactive) {
        terminal.writeErrorln('${existing.length} file(s) already exist; pass --force to overwrite.');
        exit(1);
      }

      final relative = [for (final path in existing) p.relative(path, from: configuration.root.path)];
      terminal.warn('The following file(s) will be overwritten:\n\n${relative.join('\n')}');

      if (!confirm(message: 'Overwrite ${existing.length} existing file(s)?', initial: false)) {
        terminal.cancel('No theme created.');
        exit(130);
      }
    }
  }

  await installTypography(preset, configuration.root, directory: configuration.fonts, force: force);
  await installIcons(preset, configuration.root);

  final files = {
    themePath: '${_themeHeader(preset.encode(), preset.icon.import)}\n${neutral.source}\n',
    colorsPath: '${_colorsHeader(themeFileName)}\n${colors(preset)}\n',
    typographyPath: '${_typographyHeader(themeFileName)}\n${generateTypography(preset)}\n',
    stylePath: '${_styleHeader(themeFileName)}\n${style(preset)}\n',
    iconsPath: '${_iconsHeader(themeFileName)}\n${generateIcons(preset)}\n',
  };

  for (final MapEntry(key: path, value: content) in files.entries) {
    File(path)
      ..createSync(recursive: true)
      ..writeAsStringSync(formatter.format(content));

    final message = 'Created ${Uri.file(path)}';
    if (terminal.interactive) {
      terminal.success(message);
    } else {
      terminal.writeln(message);
    }
  }

  if (terminal.interactive) {
    terminal.note(
      'Regenerate this theme with:\n'
      '  dart run forui_cli theme create --preset ${preset.encode()}\n'
      '\n'
      'See https://forui.dev/docs/concepts/themes for more information on themes.',
      title: 'Preset ${preset.encode()}',
    );
  }
}

/// Generates the light and dark `FColors` for [preset], plus the neutral theme's colour extensions.
String colors(Preset preset) {
  final light = _colors(preset.base.light, preset.primary?.light, light: true);
  final dark = _colors(preset.base.dark, preset.primary?.dark, light: false);
  final stub = neutral.colors.substring(
    neutral.colors.indexOf('/// Provides convenient access to theme extensions on [FColors].'),
  );

  return 'final FColors lightColors = $light;\n\nfinal FColors darkColors = $dark;\n\n$stub';
}

String _colors(BaseColors base, PrimaryColors? primary, {required bool light}) =>
    '''
FColors(
  brightness: .${light ? 'light' : 'dark'},
  systemOverlayStyle: .${light ? 'dark' : 'light'},
  barrier: ${_color(base.barrier)},
  background: ${_color(base.background)},
  foreground: ${_color(base.foreground)},
  primary: ${_color(primary?.primary ?? base.primary)},
  primaryForeground: ${_color(primary?.primaryForeground ?? base.primaryForeground)},
  secondary: ${_color(base.secondary)},
  secondaryForeground: ${_color(base.secondaryForeground)},
  muted: ${_color(base.muted)},
  mutedForeground: ${_color(base.mutedForeground)},
  destructive: ${_color(base.destructive)},
  destructiveForeground: ${_color(base.destructiveForeground)},
  error: ${_color(base.error)},
  errorForeground: ${_color(base.errorForeground)},
  card: ${_color(base.card)},
  border: ${_color(base.border)},
  extensions: const [AppColors()],
)''';

String _color(int color) => 'Color(0x${color.toRadixString(16).padLeft(8, '0').toUpperCase()})';

/// Generates the style section for [preset], substituting custom border radii unless the default medium is selected.
String style(Preset preset) {
  if (preset.radius == Radius.medium) {
    return neutral.style;
  }

  final radius = preset.radius.radius;
  return neutral.style.replaceAll('FBorderRadius()', '''
FBorderRadius(
  xs2: ${_radius(radius.xs2)},
  xs: ${_radius(radius.xs)},
  sm: ${_radius(radius.sm)},
  md: ${_radius(radius.md)},
  lg: ${_radius(radius.lg)},
  xl: ${_radius(radius.xl)},
  xl2: ${_radius(radius.xl2)},
  xl3: ${_radius(radius.xl3)},
  pill: ${_radius(radius.pill)},
)''');
}

String _radius(double value) => value == 0 ? '.zero' : '.all(.circular($value))';
